/**
 * This class is generated by jOOQ
 */
package at.kaufmann.model;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>firmendb</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<at.kaufmann.model.tables.records.DDeptRecord> KEY_D_DEPT_PRIMARY = UniqueKeys0.KEY_D_DEPT_PRIMARY;
	public static final org.jooq.UniqueKey<at.kaufmann.model.tables.records.EEmplRecord> KEY_E_EMPL_PRIMARY = UniqueKeys0.KEY_E_EMPL_PRIMARY;
	public static final org.jooq.UniqueKey<at.kaufmann.model.tables.records.SSalgradeRecord> KEY_S_SALGRADE_PRIMARY = UniqueKeys0.KEY_S_SALGRADE_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<at.kaufmann.model.tables.records.EEmplRecord, at.kaufmann.model.tables.records.EEmplRecord> E_EMPL_IBFK_1 = ForeignKeys0.E_EMPL_IBFK_1;
	public static final org.jooq.ForeignKey<at.kaufmann.model.tables.records.EEmplRecord, at.kaufmann.model.tables.records.DDeptRecord> E_EMPL_IBFK_2 = ForeignKeys0.E_EMPL_IBFK_2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<at.kaufmann.model.tables.records.DDeptRecord> KEY_D_DEPT_PRIMARY = createUniqueKey(at.kaufmann.model.tables.DDept.D_DEPT, at.kaufmann.model.tables.DDept.D_DEPT.D_DEPTNO);
		public static final org.jooq.UniqueKey<at.kaufmann.model.tables.records.EEmplRecord> KEY_E_EMPL_PRIMARY = createUniqueKey(at.kaufmann.model.tables.EEmpl.E_EMPL, at.kaufmann.model.tables.EEmpl.E_EMPL.E_EMPNO);
		public static final org.jooq.UniqueKey<at.kaufmann.model.tables.records.SSalgradeRecord> KEY_S_SALGRADE_PRIMARY = createUniqueKey(at.kaufmann.model.tables.SSalgrade.S_SALGRADE, at.kaufmann.model.tables.SSalgrade.S_SALGRADE.S_GRADE);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<at.kaufmann.model.tables.records.EEmplRecord, at.kaufmann.model.tables.records.EEmplRecord> E_EMPL_IBFK_1 = createForeignKey(at.kaufmann.model.Keys.KEY_E_EMPL_PRIMARY, at.kaufmann.model.tables.EEmpl.E_EMPL, at.kaufmann.model.tables.EEmpl.E_EMPL.E_MGR);
		public static final org.jooq.ForeignKey<at.kaufmann.model.tables.records.EEmplRecord, at.kaufmann.model.tables.records.DDeptRecord> E_EMPL_IBFK_2 = createForeignKey(at.kaufmann.model.Keys.KEY_D_DEPT_PRIMARY, at.kaufmann.model.tables.EEmpl.E_EMPL, at.kaufmann.model.tables.EEmpl.E_EMPL.E_D_DEPTNO);
	}
}
