/**
 * This class is generated by jOOQ
 */
package at.kaufmann.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in firmendb
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table firmendb.d_dept
	 */
	public static final at.kaufmann.model.tables.DDept D_DEPT = at.kaufmann.model.tables.DDept.D_DEPT;

	/**
	 * The table firmendb.e_empl
	 */
	public static final at.kaufmann.model.tables.EEmpl E_EMPL = at.kaufmann.model.tables.EEmpl.E_EMPL;

	/**
	 * The table firmendb.s_salgrade
	 */
	public static final at.kaufmann.model.tables.SSalgrade S_SALGRADE = at.kaufmann.model.tables.SSalgrade.S_SALGRADE;
}
