/**
 * This class is generated by jOOQ
 */
package at.kaufmann.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DDept extends org.jooq.impl.TableImpl<at.kaufmann.model.tables.records.DDeptRecord> {

	private static final long serialVersionUID = -1042556814;

	/**
	 * The singleton instance of <code>firmendb.d_dept</code>
	 */
	public static final at.kaufmann.model.tables.DDept D_DEPT = new at.kaufmann.model.tables.DDept();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.kaufmann.model.tables.records.DDeptRecord> getRecordType() {
		return at.kaufmann.model.tables.records.DDeptRecord.class;
	}

	/**
	 * The column <code>firmendb.d_dept.d_deptno</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.DDeptRecord, java.lang.Long> D_DEPTNO = createField("d_deptno", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>firmendb.d_dept.d_dname</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.DDeptRecord, java.lang.String> D_DNAME = createField("d_dname", org.jooq.impl.SQLDataType.CHAR.length(20), this);

	/**
	 * The column <code>firmendb.d_dept.d_loc</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.DDeptRecord, java.lang.String> D_LOC = createField("d_loc", org.jooq.impl.SQLDataType.CHAR.length(20), this);

	/**
	 * Create a <code>firmendb.d_dept</code> table reference
	 */
	public DDept() {
		super("d_dept", at.kaufmann.model.Firmendb.FIRMENDB);
	}

	/**
	 * Create an aliased <code>firmendb.d_dept</code> table reference
	 */
	public DDept(java.lang.String alias) {
		super(alias, at.kaufmann.model.Firmendb.FIRMENDB, at.kaufmann.model.tables.DDept.D_DEPT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.kaufmann.model.tables.records.DDeptRecord> getPrimaryKey() {
		return at.kaufmann.model.Keys.KEY_D_DEPT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.kaufmann.model.tables.records.DDeptRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.kaufmann.model.tables.records.DDeptRecord>>asList(at.kaufmann.model.Keys.KEY_D_DEPT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.kaufmann.model.tables.DDept as(java.lang.String alias) {
		return new at.kaufmann.model.tables.DDept(alias);
	}
}
