/**
 * This class is generated by jOOQ
 */
package at.kaufmann.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EEmpl extends org.jooq.impl.TableImpl<at.kaufmann.model.tables.records.EEmplRecord> {

	private static final long serialVersionUID = 1552485140;

	/**
	 * The singleton instance of <code>firmendb.e_empl</code>
	 */
	public static final at.kaufmann.model.tables.EEmpl E_EMPL = new at.kaufmann.model.tables.EEmpl();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.kaufmann.model.tables.records.EEmplRecord> getRecordType() {
		return at.kaufmann.model.tables.records.EEmplRecord.class;
	}

	/**
	 * The column <code>firmendb.e_empl.e_empno</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.EEmplRecord, java.lang.Long> E_EMPNO = createField("e_empno", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>firmendb.e_empl.e_ename</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.EEmplRecord, java.lang.String> E_ENAME = createField("e_ename", org.jooq.impl.SQLDataType.CHAR.length(20), this);

	/**
	 * The column <code>firmendb.e_empl.e_job</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.EEmplRecord, java.lang.String> E_JOB = createField("e_job", org.jooq.impl.SQLDataType.CHAR.length(20), this);

	/**
	 * The column <code>firmendb.e_empl.e_mgr</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.EEmplRecord, java.lang.Long> E_MGR = createField("e_mgr", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>firmendb.e_empl.e_hiredate</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.EEmplRecord, java.sql.Date> E_HIREDATE = createField("e_hiredate", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The column <code>firmendb.e_empl.e_sal</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.EEmplRecord, java.lang.Long> E_SAL = createField("e_sal", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>firmendb.e_empl.e_comm</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.EEmplRecord, java.lang.Integer> E_COMM = createField("e_comm", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>firmendb.e_empl.e_d_deptno</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.EEmplRecord, java.lang.Long> E_D_DEPTNO = createField("e_d_deptno", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * Create a <code>firmendb.e_empl</code> table reference
	 */
	public EEmpl() {
		super("e_empl", at.kaufmann.model.Firmendb.FIRMENDB);
	}

	/**
	 * Create an aliased <code>firmendb.e_empl</code> table reference
	 */
	public EEmpl(java.lang.String alias) {
		super(alias, at.kaufmann.model.Firmendb.FIRMENDB, at.kaufmann.model.tables.EEmpl.E_EMPL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.kaufmann.model.tables.records.EEmplRecord> getPrimaryKey() {
		return at.kaufmann.model.Keys.KEY_E_EMPL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.kaufmann.model.tables.records.EEmplRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.kaufmann.model.tables.records.EEmplRecord>>asList(at.kaufmann.model.Keys.KEY_E_EMPL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<at.kaufmann.model.tables.records.EEmplRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<at.kaufmann.model.tables.records.EEmplRecord, ?>>asList(at.kaufmann.model.Keys.E_EMPL_IBFK_1, at.kaufmann.model.Keys.E_EMPL_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.kaufmann.model.tables.EEmpl as(java.lang.String alias) {
		return new at.kaufmann.model.tables.EEmpl(alias);
	}
}
