/**
 * This class is generated by jOOQ
 */
package at.kaufmann.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SSalgrade extends org.jooq.impl.TableImpl<at.kaufmann.model.tables.records.SSalgradeRecord> {

	private static final long serialVersionUID = -1533126523;

	/**
	 * The singleton instance of <code>firmendb.s_salgrade</code>
	 */
	public static final at.kaufmann.model.tables.SSalgrade S_SALGRADE = new at.kaufmann.model.tables.SSalgrade();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.kaufmann.model.tables.records.SSalgradeRecord> getRecordType() {
		return at.kaufmann.model.tables.records.SSalgradeRecord.class;
	}

	/**
	 * The column <code>firmendb.s_salgrade.s_grade</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.SSalgradeRecord, java.lang.Byte> S_GRADE = createField("s_grade", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this);

	/**
	 * The column <code>firmendb.s_salgrade.s_losal</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.SSalgradeRecord, java.lang.Long> S_LOSAL = createField("s_losal", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>firmendb.s_salgrade.s_hisal</code>. 
	 */
	public final org.jooq.TableField<at.kaufmann.model.tables.records.SSalgradeRecord, java.lang.Long> S_HISAL = createField("s_hisal", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>firmendb.s_salgrade</code> table reference
	 */
	public SSalgrade() {
		super("s_salgrade", at.kaufmann.model.Firmendb.FIRMENDB);
	}

	/**
	 * Create an aliased <code>firmendb.s_salgrade</code> table reference
	 */
	public SSalgrade(java.lang.String alias) {
		super(alias, at.kaufmann.model.Firmendb.FIRMENDB, at.kaufmann.model.tables.SSalgrade.S_SALGRADE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.kaufmann.model.tables.records.SSalgradeRecord> getPrimaryKey() {
		return at.kaufmann.model.Keys.KEY_S_SALGRADE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.kaufmann.model.tables.records.SSalgradeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.kaufmann.model.tables.records.SSalgradeRecord>>asList(at.kaufmann.model.Keys.KEY_S_SALGRADE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.kaufmann.model.tables.SSalgrade as(java.lang.String alias) {
		return new at.kaufmann.model.tables.SSalgrade(alias);
	}
}
