/**
 * This class is generated by jOOQ
 */
package at.kaufmann.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DDeptRecord extends org.jooq.impl.UpdatableRecordImpl<at.kaufmann.model.tables.records.DDeptRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 847771862;

	/**
	 * Setter for <code>firmendb.d_dept.d_deptno</code>. 
	 */
	public void setDDeptno(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>firmendb.d_dept.d_deptno</code>. 
	 */
	public java.lang.Long getDDeptno() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>firmendb.d_dept.d_dname</code>. 
	 */
	public void setDDname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>firmendb.d_dept.d_dname</code>. 
	 */
	public java.lang.String getDDname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>firmendb.d_dept.d_loc</code>. 
	 */
	public void setDLoc(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>firmendb.d_dept.d_loc</code>. 
	 */
	public java.lang.String getDLoc() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return at.kaufmann.model.tables.DDept.D_DEPT.D_DEPTNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return at.kaufmann.model.tables.DDept.D_DEPT.D_DNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return at.kaufmann.model.tables.DDept.D_DEPT.D_LOC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getDDeptno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDDname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDLoc();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DDeptRecord
	 */
	public DDeptRecord() {
		super(at.kaufmann.model.tables.DDept.D_DEPT);
	}

	/**
	 * Create a detached, initialised DDeptRecord
	 */
	public DDeptRecord(java.lang.Long dDeptno, java.lang.String dDname, java.lang.String dLoc) {
		super(at.kaufmann.model.tables.DDept.D_DEPT);

		setValue(0, dDeptno);
		setValue(1, dDname);
		setValue(2, dLoc);
	}
}
