/**
 * This class is generated by jOOQ
 */
package at.kaufmann.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EEmplRecord extends org.jooq.impl.UpdatableRecordImpl<at.kaufmann.model.tables.records.EEmplRecord> implements org.jooq.Record8<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.sql.Date, java.lang.Long, java.lang.Integer, java.lang.Long> {

	private static final long serialVersionUID = -422174191;

	/**
	 * Setter for <code>firmendb.e_empl.e_empno</code>. 
	 */
	public void setEEmpno(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>firmendb.e_empl.e_empno</code>. 
	 */
	public java.lang.Long getEEmpno() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>firmendb.e_empl.e_ename</code>. 
	 */
	public void setEEname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>firmendb.e_empl.e_ename</code>. 
	 */
	public java.lang.String getEEname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>firmendb.e_empl.e_job</code>. 
	 */
	public void setEJob(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>firmendb.e_empl.e_job</code>. 
	 */
	public java.lang.String getEJob() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>firmendb.e_empl.e_mgr</code>. 
	 */
	public void setEMgr(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>firmendb.e_empl.e_mgr</code>. 
	 */
	public java.lang.Long getEMgr() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>firmendb.e_empl.e_hiredate</code>. 
	 */
	public void setEHiredate(java.sql.Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>firmendb.e_empl.e_hiredate</code>. 
	 */
	public java.sql.Date getEHiredate() {
		return (java.sql.Date) getValue(4);
	}

	/**
	 * Setter for <code>firmendb.e_empl.e_sal</code>. 
	 */
	public void setESal(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>firmendb.e_empl.e_sal</code>. 
	 */
	public java.lang.Long getESal() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>firmendb.e_empl.e_comm</code>. 
	 */
	public void setEComm(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>firmendb.e_empl.e_comm</code>. 
	 */
	public java.lang.Integer getEComm() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>firmendb.e_empl.e_d_deptno</code>. 
	 */
	public void setEDDeptno(java.lang.Long value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>firmendb.e_empl.e_d_deptno</code>. 
	 */
	public java.lang.Long getEDDeptno() {
		return (java.lang.Long) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.sql.Date, java.lang.Long, java.lang.Integer, java.lang.Long> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.sql.Date, java.lang.Long, java.lang.Integer, java.lang.Long> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return at.kaufmann.model.tables.EEmpl.E_EMPL.E_EMPNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return at.kaufmann.model.tables.EEmpl.E_EMPL.E_ENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return at.kaufmann.model.tables.EEmpl.E_EMPL.E_JOB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return at.kaufmann.model.tables.EEmpl.E_EMPL.E_MGR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field5() {
		return at.kaufmann.model.tables.EEmpl.E_EMPL.E_HIREDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return at.kaufmann.model.tables.EEmpl.E_EMPL.E_SAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return at.kaufmann.model.tables.EEmpl.E_EMPL.E_COMM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field8() {
		return at.kaufmann.model.tables.EEmpl.E_EMPL.E_D_DEPTNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getEEmpno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getEEname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getEJob();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getEMgr();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value5() {
		return getEHiredate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getESal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getEComm();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value8() {
		return getEDDeptno();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EEmplRecord
	 */
	public EEmplRecord() {
		super(at.kaufmann.model.tables.EEmpl.E_EMPL);
	}

	/**
	 * Create a detached, initialised EEmplRecord
	 */
	public EEmplRecord(java.lang.Long eEmpno, java.lang.String eEname, java.lang.String eJob, java.lang.Long eMgr, java.sql.Date eHiredate, java.lang.Long eSal, java.lang.Integer eComm, java.lang.Long eDDeptno) {
		super(at.kaufmann.model.tables.EEmpl.E_EMPL);

		setValue(0, eEmpno);
		setValue(1, eEname);
		setValue(2, eJob);
		setValue(3, eMgr);
		setValue(4, eHiredate);
		setValue(5, eSal);
		setValue(6, eComm);
		setValue(7, eDDeptno);
	}
}
