/**
 * This class is generated by jOOQ
 */
package at.kaufmann.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SSalgradeRecord extends org.jooq.impl.UpdatableRecordImpl<at.kaufmann.model.tables.records.SSalgradeRecord> implements org.jooq.Record3<java.lang.Byte, java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 1628735600;

	/**
	 * Setter for <code>firmendb.s_salgrade.s_grade</code>. 
	 */
	public void setSGrade(java.lang.Byte value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>firmendb.s_salgrade.s_grade</code>. 
	 */
	public java.lang.Byte getSGrade() {
		return (java.lang.Byte) getValue(0);
	}

	/**
	 * Setter for <code>firmendb.s_salgrade.s_losal</code>. 
	 */
	public void setSLosal(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>firmendb.s_salgrade.s_losal</code>. 
	 */
	public java.lang.Long getSLosal() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>firmendb.s_salgrade.s_hisal</code>. 
	 */
	public void setSHisal(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>firmendb.s_salgrade.s_hisal</code>. 
	 */
	public java.lang.Long getSHisal() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Byte> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Byte, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Byte, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field1() {
		return at.kaufmann.model.tables.SSalgrade.S_SALGRADE.S_GRADE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return at.kaufmann.model.tables.SSalgrade.S_SALGRADE.S_LOSAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return at.kaufmann.model.tables.SSalgrade.S_SALGRADE.S_HISAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value1() {
		return getSGrade();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getSLosal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getSHisal();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SSalgradeRecord
	 */
	public SSalgradeRecord() {
		super(at.kaufmann.model.tables.SSalgrade.S_SALGRADE);
	}

	/**
	 * Create a detached, initialised SSalgradeRecord
	 */
	public SSalgradeRecord(java.lang.Byte sGrade, java.lang.Long sLosal, java.lang.Long sHisal) {
		super(at.kaufmann.model.tables.SSalgrade.S_SALGRADE);

		setValue(0, sGrade);
		setValue(1, sLosal);
		setValue(2, sHisal);
	}
}
